name: 'Get & Cache Dependencies'
description: 'Get the dependencies and cache them.'

# inputs:
#   cache-key:
#     description: 'The key to use for the cache'
#     required: true
#   path:
#     description: 'The path to the dependencies'
#     required: true

runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
